name: Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - run: uv python install && uv sync

      - uses: typst-community/setup-typst@v3

      - name: Build all formats
        run: uv run make all

      - name: Verify outputs exist
        run: |
          test -f build/resume.pdf
          test -f build/resume.html
          test -f build/resume.md
          test -f build/index.html

      - name: Upload artifacts for inspection
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: build/
          retention-days: 7