name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  actions: read

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 2

      - name: Detect version change
        id: version
        run: |
          set -euo pipefail
          
          CURRENT=$(python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])" 2>/dev/null || grep '^version = ' pyproject.toml | cut -d'"' -f2)
          PREV=$(git show HEAD^:pyproject.toml 2>/dev/null | python3 -c "import tomllib, sys; print(tomllib.load(sys.stdin.buffer)['project']['version'])" 2>/dev/null || git show HEAD^:pyproject.toml 2>/dev/null | grep '^version = ' | cut -d'"' -f2 || echo "")
          
          if [[ -n "$CURRENT" && "$CURRENT" != "$PREV" ]]; then
            echo "tag=v$CURRENT" >> "$GITHUB_OUTPUT"
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Version changed: $PREV -> $CURRENT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No version change detected"
          fi

      - name: Download build artifacts
        if: steps.version.outputs.changed == 'true'
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.event.workflow_run.head_sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: build/

      - name: Verify artifacts
        if: steps.version.outputs.changed == 'true'
        run: |
          for file in build/resume.{pdf,html,md}; do
            [[ -f "$file" ]] || { echo "Missing: $file"; exit 1; }
          done
          ls -lh build/

      - name: Create or update GitHub Release
        if: steps.version.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
          make_latest: true
          fail_on_unmatched_files: true
          files: |
            build/resume.pdf
            build/resume.html
            build/resume.md